apiVersion: v1
kind: Service
metadata:
  name: edu
spec:
  type: NodePort
  selector:
    app: edu
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: edu # has to match .spec.template.metadata.labels
  serviceName: "edu"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: edu # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: edu
          image: u2rafi/edu:latest
          env:
          - name: BUILD_NUMBER
            value: 1
          command: ["/bin/sh"]
          args: ["-c", "uvicorn app.main:app --workers 3 --timeout-keep-alive 5000 --host 0.0.0.0 --port 8000"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: web